# CONSTANTS MODULE
MIN_TMOS_MAJOR_VERSION = 11
MIN_TMOS_MINOR_VERSION = 4
DEFAULT_HOSTNAME = 'bigip1'
MAX_HOSTNAME_LENGTH = 128
DEFAULT_FOLDER = "/Common"
# CONNECTION_TIMEOUT MUST BE LESS THAN 90 OR THE
# SCRIPT ENGINE WILL FAIL WITHOUT A FAULT
SCRIPT_TIMEOUT = 90
CONNECTION_TIMEOUT = 30
# DEVICE LOCK PREFIX
DEVICE_LOCK_PREFIX = 'lock_'
# DIR TO CACHE WSDLS.  SET TO NONE TO READ FROM DEVICE
# WSDL_CACHE_DIR = "/data/iControl-11.4.0/sdk/wsdl/"
WSDL_CACHE_DIR = ''
# HA CONSTANTS
HA_VLAN_NAME = "/Common/HA"
HA_SELFIP_NAME = "/Common/HA"
# VIRTUAL SERVER CONSTANTS
VS_PREFIX = 'vs'
# POOL CONSTANTS
POOL_PREFIX = 'pool'
# POOL CONSTANTS
MONITOR_PREFIX = 'monitor'
# VLAN CONSTANTS
VLAN_PREFIX = 'vlan'
# BIG-IP PLATFORM CONSTANTS
BIGIP_VE_PLATFORM_ID = 'Z100'
# DEVICE CONSTANTS
DEVICE_DEFAULT_DOMAIN = ".local"
DEVICE_HEALTH_SCORE_CPU_WEIGHT = 1
DEVICE_HEALTH_SCORE_MEM_WEIGHT = 1
DEVICE_HEALTH_SCORE_CPS_WEIGHT = 1
DEVICE_HEALTH_SCORE_CPS_PERIOD = 5
DEVICE_HEALTH_SCORE_CPS_MAX = 100
# DEVICE GROUP CONSTANTS
PEER_ADD_ATTEMPTS_MAX = 10
PEER_ADD_ATTEMPT_DELAY = 2
# MAX RAM SYNC DELAY IS 63 SECONDS
# (3+6+9+12+15+18) = 63
SYNC_DELAY = 3
MAX_SYNC_ATTEMPTS = 6
# SHARED CONFIG CONSTANTS
SHARED_CONFIG_DEFAULT_TRAFFIC_GROUP = '/Common/traffic-group-local-only'
SHARED_CONFIG_DEFAULT_FLOATING_TRAFFIC_GROUP = '/Common/traffic-group-1'
# LOGGING PARAMETERS
LOG_MODE = 'dev'
import logging
LOG_LEVEL = logging.DEBUG
LOG_PREFIX_DEV_VALIDATE = 'device validate'
LOG_PREFIX_DEV_VALIDATE = 'device modify'
# PARSING-SPECIFIC CONSTANTS
SHARED_CONFIG_STATES = {'NOCHANGE': 0, 'CREATE': 1, 'MODIFY': 2, 'DESTROY': 3}
# DEVICE CONFIG
DEV_HOSTCFG_FOLDER_KEY = 'HostConfig'
DEV_HOSTCFG_HOSTNAME_KEY = 'HostName'
DEV_NTP_FOLDER_KEY = 'NTP'
DEV_NTP_SERVER_IP_KEY = 'NTPIpaddress'
DEV_HA_FOLDER_KEY = 'HighAvailability'
DEV_HA_SELFIP_DEST_IP_KEY = 'HASelfIpaddress'
DEV_HA_SELFIP_DEST_MASK_KEY = 'HASelfIpNetmask'
DEV_HA_VLAN_KEY = 'VLAN'
DEV_HA_IF_KEY = 'Interface'
# COMMON CONFIG
COMMON_NET_INTERNAL_CONN = 'internal'
COMMON_NET_EXTERNAL_CONN = 'external'
COMMON_NET_FOLDER_KEY = 'Networking'
COMMON_VS_FOLDER_KEY = 'VirtualServer'
COMMON_VS_DEST_IP_KEY = 'DestinationIPAddress'
COMMON_VS_DEST_MASK_KEY = 'DestinationNetmask'
COMMON_VS_PROTOCOL_KEY = 'Protocol'
COMMON_VS_REL_KEY_SUFFIX = 'VirtualServerRel'
COMMON_EXT_SELFIP_FOLDER_KEY = 'ExternalSelfIP'
COMMON_EXT_SELFIP_REL_KEY_SUFFIX = 'ExternalSelfIPRel'
COMMON_EXT_SELFIP_DEST_IP_KEY = 'ExternalSelfIPAddress'
COMMON_EXT_SELFIP_DEST_MASK_KEY = 'ExternalSelfNetmask'
COMMON_INT_SELFIP_FOLDER_KEY = 'InternalSelfIP'
COMMON_INT_SELFIP_DEST_IP_KEY = 'InternalSelfIPAddress'
COMMON_INT_SELFIP_DEST_MASK_KEY = 'InternalSelfNetmask'
COMMON_INT_SELFIP_REL_KEY_SUFFIX = 'InternalSelfIPRel'
COMMON_SELFIP_FLOATING_KEY = 'Floating'
# SLB
SLB_FUNC_KEY = 'SLB'
SLB_FUNC_POOL_KEY = 'Pool'
SLB_FUNC_POOL_DEST_PORT_KEY = 'DestinationPort'
SLB_FUNC_POOL_LB_METHOD_KEY = 'LBMethod'
SLB_FUNC_POOL_SERV_DOWN_ACT_KEY = 'ActionOnServiceDown'
SLB_FUNC_POOL_PERSISTENCE_KEY = 'Persistence'
SLB_FUNC_POOL_MONITOR_KEY = 'Monitor'
SLB_FUNC_POOL_MONITOR_ATTEMPTS_KEY = 'FailByAttempts'
SLB_FUNC_POOL_MONITOR_FREQ_KEY = 'FrequencySeconds'
SLB_FUNC_POOL_MONITOR_SEND_TEXT_KEY = 'SendText'
SLB_FUNC_POOL_MONITOR_RECV_TEXT_KEY = 'ReceiveText'
SLB_FUNC_POOL_MONITOR_TYPE_KEY = 'Type'
# SOURCE IP LIMITER
SRC_IP_LIMIT_FUNC_KEY = 'SourceIPLimiter'
SRC_IP_LIMIT_FOLDER_KEY = 'SourceIPLimiterParams'
SRC_IP_LIMIT_COUNTRY_KEY = 'GeoIPCountry'
SRC_IP_LIMIT_PRIV_NET_KEY = 'PrivateNetworks'
SRC_IP_LIMIT_RULE_NAME = 'src_ip_limiter'
SRC_IP_LIMIT_RULE_PRIORITY = 100
SRC_IP_LIMIT_RULE_SRC_BASE64 = ('d2hlbiBSVUxFX0lOSVQgew0KICBzZXQgc3RhdGl'
                                 'jOjpwcml2YXRlX25ldHNfYWxsb3dlZCAkJFBSSV'
                                 'ZBVEVfTkVUU19BTExPV0VEJCQNCiAgc2V0IHN0Y'
                                 'XRpYzo6Y291bnRyeV9hbGxvd2VkICQkQ09VTlRS'
                                 'WV9BTExPV0VEJCQNCn0NCg0Kd2hlbiBDTElFTlR'
                                 'fQUNDRVBURUQgew0KICAgIGlmIHsgW2NsYXNzIG'
                                 '1hdGNoIFtJUDo6Y2xpZW50X2FkZHJdIGVxdWFsc'
                                 'yBwcml2YXRlX25ldF0gfSB7DQogICAgICBpZiB7'
                                 'ICRzdGF0aWM6OnByaXZhdGVfbmV0c19hbGxvd2V'
                                 'kICE9IDEgfSB7DQogICAgICAgIGRyb3ANCiAgIC'
                                 'AgIH0NCiAgICB9IGVsc2VpZiB7IFt3aGVyZWlzI'
                                 'FtJUDo6Y2xpZW50X2FkZHJdIGNvdW50cnldIG5l'
                                 'ICRzdGF0aWM6OmNvdW50cnlfYWxsb3dlZCB9IHs'
                                 'NCiAgICAgIGRyb3ANCiAgICB9DQp9')
SRC_IP_LIMIT_RULE_PRIV_NET_VAR = '$$PRIVATE_NETS_ALLOWED$$'
SRC_IP_LIMIT_RULE_COUNTRY_VAR = '$$COUNTRY_ALLOWED$$'
