language: ruby
rvm:
- 2.1
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
cache: bundler
script: 
 - ./docScript.sh
# whitelist
branches:
 only:
  - master
  - develop
deploy:
  provider: s3
  access_key_id: AKIAJXW2OUXQMW3DE7PA
  secret_access_key:
    secure: $AWS_ACCESSKEY
  bucket: jodietestsite
  skip_cleanup: true 
  acl: private
  local_dir: "build"
  upload-dir: "lbaasv1"
  on:
    repo: $TRAVIS_REPO_SLUG
    branch: develop
