sudo: required

services:
  - docker

script:
  - make package

deploy:
  provider: releases
  api_key:
    secure: ikSQ8t+CSrqOokNpbnSL77EOG09473MgSKTH6bDbkxipEFgxgY0fsZzuCwypzvZOzwj8rcKBRWRvNwIs+g4+aeRMV+xAa0oGprr7Cg7PLgN3w6JuXU949IG9lu0+Futa0UwO14HVTOgLJ1mFWDqQGtkFSjeDygDWS0LJjqqrMCP3GHo0VUVQvcOKHmVATt2jU5iuKRxsR6qkrZVvQtnrWD1PW4DggKm28mEapuL6M4koUJC/VUJn77DRkawsnZPx/QPeZD3z5vqUF+LkdKO4YWzzvxcllpEaG2i9cAjIobovsJh9ms6i42Kn2RbAM36dO/VAQD6/fDxzyxFTQBueDEchaz/q73r/iXPOKiSS2QiIJivXlcYIN+hYLCmEI7S1d/xy4+EH8DdeZ9sAQv4PMx822st7ZFv5AWZ+9oER4l0fd9dwK5AQnPTtkqBH3XUx4QwCK/4s4SJtBrxqmeOU3dPQJjxB0e+eDEwtksWTngv3CfOl84jMblW0SMMxUNEdmVBXTNMYWpdU4QMvI9vYItQe/j7bfl7pVmCwY2AW3VovQicBZzk8cnxLMrk4YtX8GI3/cNBe26voYsncuTEzrKVPqqp6xEMD3xX9Obov7+5aS+0Dqk8rB7O1tRgGICAYSE3Y1clUWyJXyWmXbMztXFogKwjBvt0nO76N1rKA0Vk=
  file: build/f5-lbaas_$TRAVIS_TAG.tgz
  skip_cleanup: true
  on:
    repo: F5Networks/f5-openstack-lbaasv1
    tags: true

notifications:
  slack:
    rooms:
      - f5openstackdev:$SLACK_TOKEN#f5-openstack-lbaasv1
      - f5openstackdev:$SLACK_TOKEN#build_status
    on_success: change
    on_failure: always