# This section configures testing and deployment of the docs
language: ruby
rvm:
- 2.1
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
cache: bundler
before_install:
 - script/buildDocs.sh
script: 
 - script/docScript.sh
# whitelist
branches:
 only:
  - master
  - develop
deploy:
  provider: s3
  region: us-west-2
  access_key_id: AKIAJXW2OUXQMW3DE7PA
  secret_access_key:
    secure: $AWS_ACCESSKEY
  bucket: f5-openstack-dev
  skip_cleanup: true 
  acl: authenticated_read
  local_dir: $HOME/f5-os-lbaasv1
  upload-dir: "f5-os-lbaasv1"
  on:
    repo: $TRAVIS_REPO_SLUG
    branch: $TRAVIS_BRANCH
