# This section configures testing and deployment of the docs
language: ruby
rvm:
- 2.1
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
cache: bundler
script: 
 - script/project_buildScript.sh
# whitelist
branches:
 only:
  - master
  - develop
deploy:
  provider: s3
  region: us-west-2
  access_key_id: AKIAJXW2OUXQMW3DE7PA
  secret_access_key:
    secure: $AWS_ACCESSKEY
  bucket: f5-openstack-dev-lbaas
  skip_cleanup: true 
  local_dir: $HOME/site_build/
 #upload-dir: "f5-os-lbaasv1"
  on:
    repo: $TRAVIS_REPO_SLUG
    all_branches: true
