language: ruby
rvm:
- 2.1
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
script: "docbuild.sh"
deploy:
  provider: s3
  access_key_id: AKIAJXW2OUXQMW3DE7PA
  secret_access_key:
    secure: $AWS_ACCESSKEY
  bucket: jodietestsite
  skip_cleanup: true 
  acl: private
  local_dir: "lbaasv1"
  on:
    repo: $TRAVIS_REPO_SLUG
