#Site settings
baseurl: f5-os-lbaasv1/ # the subpath of your site, e.g. /blog/

# Custom vars
current_version: 1.0.10
repo: https://github.com/F5Networks/openstack-f5-lbaasv1
brand: F5 Networks
github_username: F5Networks
product: LBaaSv1

defaults:
 - 
  scope:
    path: "doc"
    type: "pages"
  values:
    layout: "docs_page"

lsi: BOOL

<<<<<<< HEAD
includes_dir: ./_includes/f5-os-lbaasv1/
=======
includes_dir: ./doc/_includes
>>>>>>> 38abf0e... Fixes: travis build 81 failed


